/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import fachadas.FachadaJPA;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objetosNegocio.ReqReactivo;
import persistencia.ReqReactivoJpaController;

/**
 *
 * @author Francisco
 */
public class VentanaInventarioReactivos extends javax.swing.JFrame {

    DefaultTableModel dtm;
    public static EntityManagerFactory emf = Persistence.createEntityManagerFactory("laboratorioPersistenciaJPAPU");
    FachadaJPA facade = new FachadaJPA();
    ReqReactivo reqReactivo = new ReqReactivo();
    ReqReactivoJpaController jpaReqRea = new ReqReactivoJpaController();
//    Analisis analisis = new Analisis();
//    AnalisisJpaController jpaAnalisis = new AnalisisJpaController();
//    Producto productos = new Producto();
//    ProductoJpaController jpaProducto = new ProductoJpaController();

    /**
     * Creates new form VentanaAnalisis
     */
    public VentanaInventarioReactivos() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarRequerimientosReactivos();
    }

    private void mostrarRequerimientosReactivos() {
        setModelRequerimientoMateriales(tablaReqReactivos);
        DefaultTableModel modelo = (DefaultTableModel) tablaReqReactivos.getModel();
        try {
            jpaReqRea.insertarModelo(modelo);
        } catch (Exception e) {
            Logger.getLogger(VentanaProductos.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void setModelRequerimientoMateriales(JTable table) {
        while (table.getRowCount() > 0) {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaReqReactivos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA INVENTARIO REACTIVOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null), "Lista de Requerimiento Reactivos"));

        tablaReqReactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Cantidad", "Clave Producto", "Clave Analisis"
            }
        ));
        tablaReqReactivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(tablaReqReactivos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 22, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInventarioReactivos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaReqReactivos;
    // End of variables declaration//GEN-END:variables
}
